### ISSUE TITLE
Official candidates from UNSTAT process.

### ISSUE THREAD

**Issue by brunosan** [SDG-data/SDGs#27]
There seems to be already an official list of candidates:

[pdf](http://unstats.un.org/sdgs/files/List%20of%20Indicator%20Proposals%2011-8-2015.pdf)
[xls](http://unstats.un.org/sdgs/files/open-consultation-iaeg/Summary%20of%20Comments%20on%20Indicator%20Proposals%2025-9-15.XLSX)

"made available 11 August 2015"

This is the one to be approved at the next annual meeting of the International Statistical Commission. We should integrate it.

**Comment by pythagoraswitch** [comment]
This is done in the branch UNSTAT-indicators.
