### ISSUE TITLE
Add ids to Indicators

### ISSUE THREAD

**Issue by brunosan** [SDG-data/SDGs#29]
Latest proposal has Ids for Indicators. Include them.

Related to #27

**Comment by pythagoraswitch** [comment]
Currently in the branch https://github.com/SDG-data/SDGs/tree/UNSTAT-indicators , reflecting the results from UNSTAT open consultation in [Sep](http://unstats.un.org/sdgs/iaeg-sdgs/open-consultation/) and [Nov](http://unstats.un.org/sdgs/iaeg-sdgs/open-consultation-2/). The result from [December](http://unstats.un.org/sdgs/iaeg-sdgs/open-consultation-3/) will be reflected soon.

**Comment by pythagoraswitch** [comment]
Done. The numbering is generally based on [this list](http://unstats.un.org/sdgs/files/meetings/iaeg-sdgs-meeting-02/Outcomes/Agenda%20Item%204%20-%20Review%20of%20proposed%20indicators%20-%202%20Nov%202015.pdf) except some indicators that were added during green indicator open consultation.

**Comment by brunosan** [comment]
:heart:
